### ISSUE TITLE
DANCo Fast

### ISSUE THREAD

**Issue by njcprice** [j-bac/scikit-dimension#8]
Hi,

I noticed in the DANCo.py file that some functions have been commented out which seem to implement a version of FastDANCo. I was wondering if it's safe to uncomment and use these in my code or whether there was a reason as to why they're commented out?

Thanks.

P.S. Great package.

**Comment by j-bac** [comment]
Hi, thanks for using the package !

That is correct, this is a draft for FastDANCo/DANCoFit, which should work but is pending some validation tests, so I kept it commented out. 

It is probably best if you generate your own precomputed interpolation files, this way you can pre-train FastDANCo according to your preferred range and coarse-graining of cardinalities and expected intrinsic dimension.

I reuploaded for you the file skdim.id.DANCoUtils which contains the code to precompute splines. E.g., to train splines for cardinalities between [100, 500] and intrinsic dimension up to 100:
```python
dHat,mu,tau,DANCo_splines = DANCoTrain(k=10, D=100, cardinalities=[100,200,500]), iterations=100, save_output_path='')
dHat,mu,tau,DANCo_splines = load_DANCoTrain_results(path='')
plot_DANCoTrain([100,200,500],dHat,mu,tau,DANCo_splines)
```
DANCoTrain is the essential line, it will generate 3 .pkl files which you can put in the skdim.id.DANCoFit/ folder

Then you can uncomment lines 205 - 312 and 361 - 367 in skdim.id.DANCo and you should be able to use FastDANCo with skdim.id.DANCo(ver='DANCoFit')

**Comment by njcprice** [comment]
Thanks so much, man. That's really appreciated.
